- {{cookiecutter.extension_name}}/.gitignore
There's a gitignore in the root, but it's also handy to have one
in the generated project so would-be extension writers don't have
to figure out what should and should not be checked into git.
> Ignore built files in the generated project

- {{cookiecutter.extension_name}}/package.json
This
- adds all the extension types that are [currently allowed](https://jupyterlab-tutorial.readthedocs.io/en/latest/extensions_dev.html#extension-authoring)
- handles subdirectories
Both of these have tripped me up in the move to `npm`-style extensions.
Some follow-ons based on my experiences:
- add the simplest of css, 
- with the pattern of `src` and `lib` both referring to styles from `../style`... 
- I love `import("./style.css")` from a component for keeping code clean, but it is indeed simpler the way it is done now
- add the simplest `tsc --watch`
- add the simplest `jupyterlab build`
- add the simplest `jupyterlab extension link` 
- add the simplest test with `karma` or whatever
- add `tslint` (and watch): the defaults (which people's editors might pick up) don't reflect the …
> Add supported extension types and subdirectories

- {{cookiecutter.extension_name}}/package.json
This should help with discoverability of published extensions, as it is a very specific keyword.
> Ensure keyword "jupyterlab extension"

- {{cookiecutter.extension_name}}/tsconfig.json
"ES5", "ES2015.Promise", -> `"ES6"`. Closes https://github.com/jupyterlab/jupyterlab/issues/4770
> ES6 lib tsconfig

- {{cookiecutter.extension_name}}/README.md
Creating a new extension from this cookiecutter wouldn't work for 0.30 <= jupyterlab < 1.0.
> Update JLab min version in README

- {{cookiecutter.extension_name}}/package.json
To be consistent with the [documentation](https://jupyterlab.readthedocs.io/en/stable/developer/extension_tutorial.html#extension-tutorial), we should use `jlpm` instead `npm` in `package.json` scripts.
Note: I simplify the `rimraf` syntax in this PR.
> Switch to jlpm

- {{cookiecutter.extension_name}}/.github/workflows/build.yml
- {{cookiecutter.extension_name}}/README.md
Now that GitHub Actions have been rolled out to everyone, we can add a simple workflow to make sure the extension can be built.
This means that CI will be on and enabled by default if the extension is being developed on GitHub.
This change also adds a badge to the README file.
> Add GitHub Actions workflow to build the extension

- {{cookiecutter.extension_name}}/LICENSE
In the `package.json` of the extension, a default license is mentioned: `BSD-3-Clause`
It seems coherent to include the corresponding license file in the extension.
> Add license in extension

- {{cookiecutter.extension_name}}/README.md
- {{cookiecutter.extension_name}}/package.json
This change should remove the empty lines (mostly in `package.json`) when using the cookiecutter without the server extension part:
```json
{
"scripts": {
"build": "tsc",
"clean": "rimraf lib tsconfig.tsbuildinfo",
"eslint": "eslint . --ext .ts,.tsx --fix",
"eslint:check": "eslint . --ext .ts,.tsx",
"prepare": "jlpm run clean && jlpm run build",
"watch": "tsc -w"
},
"dependencies": {
"@jupyterlab/application": "^2.0.0"
},
"devDependencies": {
"@typescript-eslint/eslint-plugin": "^2.25.0",
"@typescript-eslint/parser": "^2.25.0",
"eslint": "^6.8.0",
"eslint-config-prettier": "^6.10.1",
"eslint-plugin-prettier": "^3.1.2",
"prettier": "1.16.4",
"rimraf": "^2.6.1",
"typescript": "~3.7.0"
},
"sideEffects": [
"style/*.css"
],
"jupyterlab": {
"extension": true
}
}
```
> Remove empty lines if no server extension

- cookiecutter.json
- cookiecutter_with_server.json
- hooks/post_gen_project.py
- {{cookiecutter.extension_name}}/README.md
- {{cookiecutter.extension_name}}/binder/environment.yml
- {{cookiecutter.extension_name}}/binder/labextensions.txt
- {{cookiecutter.extension_name}}/binder/postBuild
While having GitHub CI is cool, demos are even cooler for getting people spun up and experiencing shareable success quickly.
This adds an opt-in `has_binder` switch which will create a fairly-opinionated binder (or local) environment based on a `binder` folder with:
- an `environment.yml`
- because binder is already conda-based, and will predictably work on windows
- and pinning node/lab versions is a Good Thing
- a python-based `postBuild`
- because bash is scary, see point above about windows
- a simple `labextensions.txt` with the extension-under-demo as well as some recommendations
- because we don't have a "real" file description
Also further populated badgeopolis in the README.
I haven't added anything to the tests... maybe should be black/flake8 checking output python, but …
> Add an opt-in binder

- {{cookiecutter.extension_name}}/README.md
This enables the extension only in the current venv/conda env.
Anywhere else, the extension will fail to load as the package
isn't available.
> Enable serverextension under sys.prefix

- {{cookiecutter.extension_name}}/src/{{cookiecutter.extension_name}}.ts
Some request like DELETE have no response body. This change the code to ready the response body as text and convert it to JSON only if it is not empty.
> Parse response as data if it is not empty

- {{cookiecutter.extension_name}}/README.md
- Use install instead of link (https://gitter.im/jupyterlab/jupyterlab?at=5ee6abf324a3382d5d68b2ae)
- mention the need to refresh the page after rebuild
- Wording copied wholesale from the jupyterlab-git readme
> Update development install instructions

- .github/workflows/main.yml
The periodic CI check started to fail a couple of days ago.
Here is an example of such build: https://github.com/jupyterlab/extension-cookiecutter-ts/runs/820559135?check_suite_focus=true
This is because CI was installing a pre-release version of JupyterLab.
> Use a stable lab version on CI instead of a prerelease

- {{cookiecutter.python_name}}/pyproject.toml
- {{cookiecutter.python_name}}/setup.py
Fixes https://github.com/jupyterlab/extension-cookiecutter-ts/issues/92
Puts the allowed range to the entire 3.x range (from b6 and up).
> Update python lab version specifier

- {{cookiecutter.python_name}}/setup.py
While upgrading an extension that has a setting file, the wheel didn't contain the `schemas` directory but the `sdist` did.
This change updates the glob pattern to also include nested directories such as settings files for extensions.
> Update data_files_spec glob to include nested directories

- {{cookiecutter.python_name}}/package.json
- {{cookiecutter.python_name}}/setup.py
Fixes #96 
Using `build:prod` so it stays similar to core lab:
https://github.com/jupyterlab/jupyterlab/blob/46681a918408f4fa910b78a2825e96d6a4cbb487/jupyterlab/staging/package.json#L9
> `jlpm run build` builds with --development by default

- {{cookiecutter.python_name}}/setup.py
- {{cookiecutter.python_name}}/{{cookiecutter.python_name}}/_version.py
This PR makes it so that version is fetched from <ext-name>'s `package.json` during installation of the python package in `setup.py`, and when someone does `import <ext-name>; <ext-name>.__version__`.
To give some extra flexibility w.r.t. project structure, the version lookup for `<ext-name>.__version__` will look for `package.json` in the install dir of the `<ext-name>` python package, as well as any subdirs. This is needed for the default python package produced by the cookiecutter, which currently places `package.json` at `<ext-name>/static/package.json`.
> Treat package.json as sole source of version truth, get python version from that

- .github/workflows/main.yml
To match: 
https://github.com/jupyterlab/jupyterlab/blob/05e704f20cc3358e3066adef8273a602a3f76e91/.github/workflows/linuxjs-tests.yml#L22
And the bump to node 12 in the latest lab as minimal requirement.
> Use Node 12 on CI

- {{cookiecutter.python_name}}/README.md
Follow-up to https://github.com/jupyterlab/extension-cookiecutter-ts/pull/109
> Remove jupyter labextension uninstall from README

- .github/workflows/main.yml
- {{cookiecutter.python_name}}/pyproject.toml
- {{cookiecutter.python_name}}/setup.py
Using `skip_if_exists` from `jupyter_packaging` added in https://github.com/jupyter/jupyter-packaging/pull/54
This avoids rebuilding the assets if they already exist (for example in the source tarball).
The main motivation is to make it easier to package for conda, to avoid the dependency on `jupyterlab` / `jlpm`.
> Skip building js assets if they already exist

- {{cookiecutter.python_name}}/setup.py
Since `lib` is pruned here:
https://github.com/jupyterlab/extension-cookiecutter-ts/blob/fb8de6e99ee29ea0f11aecf1f49b044e1023e319/%7B%7Bcookiecutter.python_name%7D%7D/MANIFEST.in#L16
It will not be part of the sdist, and will be a missing js target. Which means that even with https://github.com/jupyterlab/extension-cookiecutter-ts/pull/121, it looks like it will still trigger a build.
Not sure we could rely on any other files in `outputDir/static/` since their names are generated. So we might just want to keep `outputDir/package.json`?
> Remove the lib js target

- {{cookiecutter.python_name}}/.github/workflows/build.yml
- {{cookiecutter.python_name}}/README.md
Now github [default](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/#:~:text=The%20default%20branch%20name%20for,.com%2Fsettings%2Frepositories%20page) branch name is `main` rather than `master`. The new extension projects built from the template should be modified as well.
> Change the default branch from master to main

- {{cookiecutter.python_name}}/setup.py
Since the 3.0 branch pulls info from JSON anyway, why not all of it?
> Centralize info

- {{cookiecutter.python_name}}/MANIFEST.in
When installing from an sdist, pip will run the bdist_wheel command, rebuilding the JS source. This cookicutter currently uses `jlpm` as the install command. For this reason it makes sense to include the yarn.lock file (a set of dependencies that are known to produce a working build).
> Include yarn.lock in manifest

- {{cookiecutter.python_name}}/.eslintrc.js
- {{cookiecutter.python_name}}/.prettierignore
- {{cookiecutter.python_name}}/.prettierrc
- {{cookiecutter.python_name}}/package.json
This is particularly important to support some Typescript features of 3.7+
https://github.com/typescript-eslint/typescript-eslint/releases/tag/v4.0.0
> Align linter with JupyterLab
