jupyterlab/extension-cookiecutter-ts

{{cookiecutter.extension_name}}/setup.py
See https://github.com/jupyterlab/jupyterlab/issues/1113 and https://github.com/jupyterlab/extension-cookiecutter-js/pull/9
=> Add Keywords To Setup Metadata

.travis.yml, {{cookiecutter.extension_name}}/.gitignore, {{cookiecutter.extension_name}}/package.json, {{cookiecutter.extension_name}}/src/index.ts
To be released after JupyterLab 0.28 final.
=> Update for JupyterLab 0.28

{{cookiecutter.extension_name}}/package.json
cf https://github.com/jupyterlab/jupyterlab/issues/3145
=> Use prepack script

{{cookiecutter.extension_name}}/package.json
=> Update for JupyterLab 0.32

.gitignore, {{cookiecutter.extension_name}}/package.json, {{cookiecutter.extension_name}}/src/index.ts, {{cookiecutter.extension_name}}/tsconfig.json
Don't merge just yet, just keep this as a branch in this repo.
=> Update for JLab 1.0.0

.github/workflows/main.yml, {{cookiecutter.extension_name}}/.eslintignore, {{cookiecutter.extension_name}}/.eslintrc.js, {{cookiecutter.extension_name}}/.github/workflows/build.yml, {{cookiecutter.extension_name}}/.prettierignore, {{cookiecutter.extension_name}}/.prettierrc, {{cookiecutter.extension_name}}/package.json, {{cookiecutter.extension_name}}/src/index.ts
To help user start with good practices and reduce the difference with the extension examples configuration, this add _eslint_ and _prettier_ on the extension template.
=> Add eslint and prettier

{{cookiecutter.extension_name}}/.eslintrc.js, {{cookiecutter.extension_name}}/.gitignore, {{cookiecutter.extension_name}}/package.json
Small improvements following the update of the server extension example.
=> ENH following server-extension example update

{{cookiecutter.extension_name}}/package.json
Fixes #69. 
Also update a couple of other `devDependencies`.
=> Update to TypeScript 3.9

{{cookiecutter.python_name}}/binder/environment.yml
=> Update nodejs to 14 in binder

.github/workflows/main.yml, {{cookiecutter.python_name}}/package.json, {{cookiecutter.python_name}}/setup.py, {{cookiecutter.python_name}}/{{cookiecutter.python_name}}/__init__.py
cf https://github.com/jupyterlab/jupyterlab/issues/8870#issuecomment-681911622
Also upgrades to JupyterLab beta 1
=> Add an install:extension helper script

{{cookiecutter.python_name}}/package.json
Make sure we are installed before running watch
=> Fix watch script

{{cookiecutter.python_name}}/package.json
Part of work for https://github.com/jupyterlab/jupyterlab/pull/8974
=> Defer pip install to python scripts

{{cookiecutter.python_name}}/package.json, {{cookiecutter.python_name}}/setup.py
=> `jlpm run build` builds all

.github/workflows/main.yml, .gitignore, {{cookiecutter.python_name}}/.gitignore, {{cookiecutter.python_name}}/README.md, {{cookiecutter.python_name}}/package.json, {{cookiecutter.python_name}}/pyproject.toml, {{cookiecutter.python_name}}/setup.py
A few small updates, including fixing the gitignore and adding a dev build command.
=> Updates for jlab 3

.github/workflows/main.yml, {{cookiecutter.python_name}}/package.json, {{cookiecutter.python_name}}/pyproject.toml, {{cookiecutter.python_name}}/setup.py
cc @jasongrout @afshin 
Thanks for the release!
=> Update for rc0

{{cookiecutter.python_name}}/.github/workflows/build.yml
This corresponds to the GitHub Actions workflow for the extension itself after it has been generated.
=> Update CI workflow to install the lab ext with pip

{{cookiecutter.python_name}}/package.json
Which is now also used in core lab.
=> Update to TypeScript 4

{{cookiecutter.python_name}}/README.md
Fixes https://github.com/jupyterlab/jupyterlab/issues/9238
=> Add instructions to generate the lab source maps

{{cookiecutter.python_name}}/package.json
To match the PR in JupyterLab: https://github.com/jupyterlab/jupyterlab/pull/9476
=> Update to TypeScript 4.1.3

.github/workflows/main.yml, {{cookiecutter.python_name}}/package.json, {{cookiecutter.python_name}}/pyproject.toml, {{cookiecutter.python_name}}/setup.py, {{cookiecutter.python_name}}/style/index.css, {{cookiecutter.python_name}}/style/index.js
To make things consistent with https://github.com/jupyterlab/jupyterlab/pull/9460
=> Add styleModule files

.github/workflows/main.yml, {{cookiecutter.python_name}}/package.json, {{cookiecutter.python_name}}/pyproject.toml, {{cookiecutter.python_name}}/setup.py
Update to using the latest packages.
=> Update to JupyterLab 3.0 final

cookiecutter.json
This just makes the defaults more intelligent to use previous values the user has entered.
=> Make defaults for parameters more sensible

.github/workflows/main.yml
Don't duplicate testing on push and PR
=> Simplify checking the template
